#!/bin/bash

PATH_TO_FILE=___

IP_ADDR=`grep -A 3 $1 $PATH_TO_FILE | grep IP-адрес | tr -d ' ' | cut -d ':' -f2`
PASSWORD=`grep -A 3 $1 $PATH_TO_FILE | grep Пароль | tr -d ' ' | cut -d ':' -f2`

sshpass -p $PASSWORD ssh root@$IP_ADDR
